### ISSUE TITLE
How to use this app

### ISSUE THREAD

**Issue by saputrasaja** [rubeus90/WonderCom#1]
Hi i already clone this repo and i think its really good to learn some think new, but i don't know how to using this app.

Can u help us, to describe step" by step using this app after installing WonderCom.apk please

**Comment by rubeus90** [comment]
Hi,

You cannot connect your devices together inside the app (I've not implemented that because it doesn't work very well on my test phones at the time). So you have to do the connection step manually. Usually you can do that in the device's settings menu -> Wifi -> Advanced -> choose the name of the device you want to connect to

Once your devices are connected, you can return to my app, then you'll see a form to enter your chat name (required), and a button to start the chat room. **Attention, one of the devices is marked as the server, you have to start the chat room with this device first, or else it'll not work.**

Then TADAA, you can now send messages between your devices ^^

**Comment by saputrasaja** [comment]
I already doing before
One device act like server on menu setting -> wireless & networks -> more -> Tethering & portable hotspot -> wi-fi hotspot then activate it
Other device act like client, same like usual process connect to wireless

Then on server show users with address and "block" button.
I think it already connecting each other

But went the device server  start this app, it show toast message "Wifi p2p not supported by this device"
Is that mean my device server cant using this app ? to be act like server ?

Then start app on the client device and show toast "Wifi p2p supported by this device"

**Comment by rubeus90** [comment]
You've activated the wrong option in menu settings, you've activated the Wifi tethering, whereas my application needs Wifi Direct.
Like I said before, the Wifi Direct option is in Settings -> Wifi -> Advanced -> Wifi Direct (or Settings -> Wifi -> Wifi Direct on Samsung devices). The menu for Wifi Direct looks and works similarly to the Bluetooth menu, you have to connect your devices 2 by 2.

Anyway, the toast messages don't depend on whether you've enabled Wifi Direct or not, they actually tell you if your device supports this technology. So if you see the toast "Wifi p2p not supported" then my app cannot work with that device, sorry!

**Comment by saputrasaja** [comment]
Ah i see that, i thought there are same one

Thanks for explaining :)
